baseURL = 'https://blog.infomaniac.co.za/'
languageCode = 'en-us'
title = "Danny Kopping's Blog"
theme = 'archie'
copyright = "© Danny Kopping"
[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Senior Software Engineer @ Grafana Labs / Cape Town, South Africa"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/dannykopping"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/dannykopping/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1
